version: '3.8'
services:
  # service for database
  db:
    image: postgres:15.2-alpine3.17
    restart: always
    environment:
      - POSTGRES_USER=example
      - POSTGRES_PASSWORD=12345
    ports:
      - '5432:5432'
    volumes:
      # initial queri and persistence of data
      - ./src/test/resources/db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql

  # service for adminer database
  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - 8081:8080