version: '3.8'
services:
  # Para el contenedor de la base de datos:
  db:
    image: postgres:15.2-alpine3.17
    restart: always
    environment:
      - POSTGRES_USER=example
      - POSTGRES_PASSWORD=12345
    ports:
      - '5432:5432'
    volumes:
      # Para que ejecute queris al inicializar
      - ./src/test/resources/db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql

  # Para ver la base de datos
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080